apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: postgres-demo-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-deploy
    app: postgres-demo-deploy