apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: redis-demo-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-deploy
    app: redis-demo-deploy