apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    name: results-service
    app: results-demo-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: results-app-demo
    name: results-app-prod