apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: voting-demo-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-app-demo
    name: voting-app-prod